/**
 * Demo / fallback data used when backend services are unavailable.
 *
 * These are shown so the UI always renders populated content during demos,
 * offline scenarios, or backend outages. All spots are real, well-known
 * public skateparks. Leaderboard entries use skater-style usernames.
 *
 * IMPORTANT: Demo spot IDs are negative to distinguish them from real
 * Postgres serial IDs. Any code that sends spot IDs to APIs MUST guard
 * against negative IDs (see isDemoSpot helper below).
 */
import type { Spot } from "@shared/schema";
import type { LeaderboardEntry } from "../features/leaderboard/useRealtimeLeaderboard";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Returns true if the spot is client-side demo data (not from the database). */
export function isDemoSpot(spot: { id: number }): boolean {
  return spot.id < 0;
}

// ---------------------------------------------------------------------------
// Demo spots — iconic real-world skate spots
// ---------------------------------------------------------------------------

const DEMO_DATE = new Date("2025-09-15T00:00:00Z");

export const DEMO_SPOTS: Spot[] = [
  {
    id: -1,
    name: "Hubba Hideout",
    description:
      "The legendary San Francisco ledge spot. Iconic for ledge tricks and part of skate history.",
    spotType: "ledge",
    tier: "legendary",
    lat: 37.7849,
    lng: -122.4094,
    address: "1 Dr Carlton B Goodlett Pl",
    city: "San Francisco",
    state: "CA",
    country: "USA",
    photoUrl: null,
    thumbnailUrl: null,
    createdBy: null,
    createdAt: DEMO_DATE,
    updatedAt: DEMO_DATE,
    verified: true,
    isActive: true,
    checkInCount: 342,
    rating: 4.9,
    ratingCount: 127,
  },
  {
    id: -2,
    name: "MACBA",
    description:
      "Museum of Contemporary Art plaza. One of the most famous street spots in the world.",
    spotType: "street",
    tier: "legendary",
    lat: 41.3833,
    lng: 2.17,
    address: "Plaça dels Àngels, 1",
    city: "Barcelona",
    state: null,
    country: "Spain",
    photoUrl: null,
    thumbnailUrl: null,
    createdBy: null,
    createdAt: DEMO_DATE,
    updatedAt: DEMO_DATE,
    verified: true,
    isActive: true,
    checkInCount: 518,
    rating: 4.8,
    ratingCount: 203,
  },
  {
    id: -3,
    name: "Venice Beach Skatepark",
    description: "Iconic oceanside skatepark with snake run, bowls, and street section.",
    spotType: "park",
    tier: "gold",
    lat: 33.985,
    lng: -118.4725,
    address: "1800 Ocean Front Walk",
    city: "Los Angeles",
    state: "CA",
    country: "USA",
    photoUrl: null,
    thumbnailUrl: null,
    createdBy: null,
    createdAt: DEMO_DATE,
    updatedAt: DEMO_DATE,
    verified: true,
    isActive: true,
    checkInCount: 891,
    rating: 4.7,
    ratingCount: 314,
  },
  {
    id: -4,
    name: "LES Coleman Park",
    description: "Lower East Side community skatepark under the Manhattan Bridge.",
    spotType: "park",
    tier: "gold",
    lat: 40.7138,
    lng: -73.9903,
    address: "Pike St & Monroe St",
    city: "New York",
    state: "NY",
    country: "USA",
    photoUrl: null,
    thumbnailUrl: null,
    createdBy: null,
    createdAt: DEMO_DATE,
    updatedAt: DEMO_DATE,
    verified: true,
    isActive: true,
    checkInCount: 267,
    rating: 4.5,
    ratingCount: 89,
  },
  {
    id: -5,
    name: "Burnside Skatepark",
    description: "DIY legend under the Burnside Bridge. Built by skaters, for skaters.",
    spotType: "diy",
    tier: "legendary",
    lat: 45.5228,
    lng: -122.6654,
    address: "E Burnside St & SE 2nd Ave",
    city: "Portland",
    state: "OR",
    country: "USA",
    photoUrl: null,
    thumbnailUrl: null,
    createdBy: null,
    createdAt: DEMO_DATE,
    updatedAt: DEMO_DATE,
    verified: true,
    isActive: true,
    checkInCount: 445,
    rating: 4.8,
    ratingCount: 167,
  },
  {
    id: -6,
    name: "FDR Skatepark",
    description: "Massive DIY skatepark under I-95 in Philadelphia. Deep bowls and transitions.",
    spotType: "diy",
    tier: "gold",
    lat: 39.9131,
    lng: -75.1821,
    address: "Pattison Ave & S Broad St",
    city: "Philadelphia",
    state: "PA",
    country: "USA",
    photoUrl: null,
    thumbnailUrl: null,
    createdBy: null,
    createdAt: DEMO_DATE,
    updatedAt: DEMO_DATE,
    verified: true,
    isActive: true,
    checkInCount: 334,
    rating: 4.6,
    ratingCount: 112,
  },
  {
    id: -7,
    name: "Southbank Undercroft",
    description: "Historic concrete banks and ledges beneath the National Theatre in London.",
    spotType: "street",
    tier: "legendary",
    lat: 51.5065,
    lng: -0.1164,
    address: "Belvedere Rd",
    city: "London",
    state: null,
    country: "UK",
    photoUrl: null,
    thumbnailUrl: null,
    createdBy: null,
    createdAt: DEMO_DATE,
    updatedAt: DEMO_DATE,
    verified: true,
    isActive: true,
    checkInCount: 612,
    rating: 4.7,
    ratingCount: 241,
  },
  {
    id: -8,
    name: "Lincoln Memorial Steps",
    description: "Classic East Coast gap and stair set. A DC staple since the 90s.",
    spotType: "stairs",
    tier: "gold",
    lat: 38.8893,
    lng: -77.0502,
    address: "2 Lincoln Memorial Cir NW",
    city: "Washington",
    state: "DC",
    country: "USA",
    photoUrl: null,
    thumbnailUrl: null,
    createdBy: null,
    createdAt: DEMO_DATE,
    updatedAt: DEMO_DATE,
    verified: true,
    isActive: true,
    checkInCount: 156,
    rating: 4.3,
    ratingCount: 58,
  },
];

// ---------------------------------------------------------------------------
// Demo leaderboard — skater-style usernames
// ---------------------------------------------------------------------------

export const DEMO_LEADERBOARD: LeaderboardEntry[] = [
  {
    id: "demo-1",
    displayName: "railSlider_sf",
    username: "railslider_sf",
    points: 12450,
    totalCheckIns: 89,
    spotsVisited: 34,
    streak: 14,
    rank: 1,
  },
  {
    id: "demo-2",
    displayName: "kickflipKing",
    username: "kickflipking",
    points: 10820,
    totalCheckIns: 76,
    spotsVisited: 28,
    streak: 11,
    rank: 2,
  },
  {
    id: "demo-3",
    displayName: "treSoul",
    username: "tresoul",
    points: 9340,
    totalCheckIns: 64,
    spotsVisited: 25,
    streak: 8,
    rank: 3,
  },
  {
    id: "demo-4",
    displayName: "heelflipHero",
    username: "heelfliphero",
    points: 8190,
    totalCheckIns: 58,
    spotsVisited: 22,
    streak: 6,
    rank: 4,
  },
  {
    id: "demo-5",
    displayName: "grindMaster_bk",
    username: "grindmaster_bk",
    points: 7650,
    totalCheckIns: 52,
    spotsVisited: 19,
    streak: 9,
    rank: 5,
  },
  {
    id: "demo-6",
    displayName: "noseslide_nyc",
    username: "noseslide_nyc",
    points: 6420,
    totalCheckIns: 45,
    spotsVisited: 17,
    streak: 5,
    rank: 6,
  },
  {
    id: "demo-7",
    displayName: "switchStance",
    username: "switchstance",
    points: 5880,
    totalCheckIns: 41,
    spotsVisited: 15,
    streak: 4,
    rank: 7,
  },
  {
    id: "demo-8",
    displayName: "poolRipper",
    username: "poolripper",
    points: 4950,
    totalCheckIns: 35,
    spotsVisited: 13,
    streak: 7,
    rank: 8,
  },
  {
    id: "demo-9",
    displayName: "ledgeLord_pdx",
    username: "ledgelord_pdx",
    points: 4210,
    totalCheckIns: 30,
    spotsVisited: 11,
    streak: 3,
    rank: 9,
  },
  {
    id: "demo-10",
    displayName: "flatground_og",
    username: "flatground_og",
    points: 3580,
    totalCheckIns: 24,
    spotsVisited: 9,
    streak: 2,
    rank: 10,
  },
];
