ALTER TABLE "consumed_payment_intents" ADD CONSTRAINT "consumed_payment_intents_user_id_custom_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."custom_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_user_id_custom_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."custom_users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "feedback" ADD CONSTRAINT "feedback_user_id_custom_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."custom_users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trick_clips" ADD CONSTRAINT "trick_clips_user_id_custom_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."custom_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trick_mastery" ADD CONSTRAINT "trick_mastery_user_id_custom_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."custom_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "closet_items" ADD CONSTRAINT "closet_items_user_id_custom_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."custom_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "onboarding_profiles" ADD CONSTRAINT "onboarding_profiles_uid_custom_users_id_fk" FOREIGN KEY ("uid") REFERENCES "public"."custom_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_profiles" ADD CONSTRAINT "user_profiles_id_custom_users_id_fk" FOREIGN KEY ("id") REFERENCES "public"."custom_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notification_preferences" ADD CONSTRAINT "notification_preferences_user_id_custom_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."custom_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_custom_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."custom_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mod_actions" ADD CONSTRAINT "mod_actions_admin_id_custom_users_id_fk" FOREIGN KEY ("admin_id") REFERENCES "public"."custom_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mod_actions" ADD CONSTRAINT "mod_actions_target_user_id_custom_users_id_fk" FOREIGN KEY ("target_user_id") REFERENCES "public"."custom_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "moderation_profiles" ADD CONSTRAINT "moderation_profiles_user_id_custom_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."custom_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "moderation_reports" ADD CONSTRAINT "moderation_reports_reporter_id_custom_users_id_fk" FOREIGN KEY ("reporter_id") REFERENCES "public"."custom_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "unique_closet_user_item" ON "closet_items" USING btree ("user_id","type","name");--> statement-breakpoint
ALTER TABLE "onboarding_profiles" ADD CONSTRAINT "onboarding_profiles_username_unique" UNIQUE("username");