import { StyleSheet } from "react-native";
import { SKATE } from "@/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: SKATE.colors.ink,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: SKATE.spacing.md,
    padding: SKATE.spacing.lg,
    paddingTop: SKATE.spacing.xl,
  },
  headerIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(255, 106, 0, 0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: SKATE.colors.white,
  },
  headerSubtitle: {
    fontSize: 14,
    color: SKATE.colors.lightGray,
  },
  tabs: {
    flexDirection: "row",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: SKATE.borderRadius.lg,
    padding: 4,
    marginHorizontal: SKATE.spacing.lg,
    marginBottom: SKATE.spacing.lg,
  },
  tab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: SKATE.spacing.xs,
    paddingVertical: SKATE.spacing.sm,
    borderRadius: SKATE.borderRadius.md,
  },
  tabActive: {
    backgroundColor: SKATE.colors.orange,
  },
  tabText: {
    fontSize: 14,
    fontWeight: "600",
    color: SKATE.colors.lightGray,
  },
  tabTextActive: {
    color: SKATE.colors.white,
  },
  content: {
    flex: 1,
  },
  uploadContainer: {
    padding: SKATE.spacing.lg,
  },
  uploadCard: {
    backgroundColor: SKATE.colors.grime,
    borderRadius: SKATE.borderRadius.lg,
    padding: SKATE.spacing.lg,
    borderWidth: 1,
    borderColor: "rgba(255, 106, 0, 0.2)",
  },
  uploadHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: SKATE.spacing.sm,
    marginBottom: SKATE.spacing.lg,
  },
  uploadTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: SKATE.colors.white,
  },
  formGroup: {
    marginBottom: SKATE.spacing.lg,
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: SKATE.colors.lightGray,
    marginBottom: SKATE.spacing.sm,
  },
  input: {
    backgroundColor: SKATE.colors.ink,
    borderWidth: 1,
    borderColor: SKATE.colors.gray,
    borderRadius: SKATE.borderRadius.md,
    padding: SKATE.spacing.md,
    color: SKATE.colors.white,
    fontSize: 16,
  },
  textArea: {
    minHeight: 80,
    textAlignVertical: "top",
  },
  visibilityToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: SKATE.spacing.sm,
    marginBottom: SKATE.spacing.lg,
  },
  visibilityBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: SKATE.spacing.xs,
    paddingHorizontal: SKATE.spacing.md,
    paddingVertical: SKATE.spacing.xs,
    borderRadius: 16,
    backgroundColor: SKATE.colors.gray,
    borderWidth: 1,
    borderColor: SKATE.colors.gray,
  },
  visibilityBadgePublic: {
    backgroundColor: "rgba(16, 185, 129, 0.1)",
    borderColor: "#10b981",
  },
  visibilityText: {
    fontSize: 12,
    fontWeight: "600",
    color: SKATE.colors.lightGray,
  },
  visibilityTextPublic: {
    color: "#10b981",
  },
  visibilityHint: {
    fontSize: 12,
    color: SKATE.colors.gray,
  },
  uploadButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: SKATE.spacing.sm,
    backgroundColor: SKATE.colors.orange,
    padding: SKATE.spacing.lg,
    borderRadius: SKATE.borderRadius.lg,
    marginBottom: SKATE.spacing.md,
  },
  uploadButtonDisabled: {
    backgroundColor: SKATE.colors.gray,
    opacity: 0.5,
  },
  uploadButtonText: {
    fontSize: 16,
    fontWeight: "bold",
    color: SKATE.colors.white,
  },
  progressContainer: {
    marginBottom: SKATE.spacing.md,
  },
  progressBar: {
    height: 8,
    backgroundColor: SKATE.colors.gray,
    borderRadius: 4,
    overflow: "hidden",
    marginBottom: SKATE.spacing.xs,
  },
  progressFill: {
    height: "100%",
    backgroundColor: SKATE.colors.orange,
  },
  progressText: {
    fontSize: 12,
    color: SKATE.colors.lightGray,
    textAlign: "center",
  },
  uploadHint: {
    fontSize: 12,
    color: SKATE.colors.gray,
    textAlign: "center",
  },
  clipsContainer: {
    padding: SKATE.spacing.lg,
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: SKATE.spacing.xl * 2,
  },
  loadingText: {
    fontSize: 14,
    color: SKATE.colors.lightGray,
    marginTop: SKATE.spacing.md,
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: SKATE.spacing.xl * 2,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: SKATE.colors.white,
    marginTop: SKATE.spacing.lg,
    marginBottom: SKATE.spacing.sm,
  },
  emptyText: {
    fontSize: 14,
    color: SKATE.colors.lightGray,
    textAlign: "center",
    marginBottom: SKATE.spacing.lg,
  },
  emptyButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: SKATE.spacing.sm,
    backgroundColor: SKATE.colors.orange,
    paddingHorizontal: SKATE.spacing.lg,
    paddingVertical: SKATE.spacing.md,
    borderRadius: SKATE.borderRadius.lg,
  },
  emptyButtonText: {
    fontSize: 16,
    fontWeight: "bold",
    color: SKATE.colors.white,
  },
  clipCount: {
    fontSize: 12,
    color: SKATE.colors.gray,
    marginBottom: SKATE.spacing.md,
  },
  clipGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SKATE.spacing.md,
  },
  clipCard: {
    width: "48%",
    backgroundColor: SKATE.colors.grime,
    borderRadius: SKATE.borderRadius.lg,
    borderWidth: 1,
    borderColor: SKATE.colors.gray,
    overflow: "hidden",
  },
  clipThumbnail: {
    aspectRatio: 9 / 16,
    backgroundColor: SKATE.colors.ink,
    position: "relative",
  },
  thumbnailImage: {
    width: "100%",
    height: "100%",
  },
  thumbnailPlaceholder: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  playIcon: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: [{ translateX: -16 }, { translateY: -16 }],
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    borderRadius: 20,
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  durationBadge: {
    position: "absolute",
    bottom: 4,
    right: 4,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  durationText: {
    fontSize: 10,
    color: SKATE.colors.white,
    fontWeight: "600",
  },
  clipInfo: {
    padding: SKATE.spacing.sm,
  },
  clipName: {
    fontSize: 14,
    fontWeight: "600",
    color: SKATE.colors.white,
    marginBottom: SKATE.spacing.xs,
  },
  clipMeta: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: SKATE.spacing.xs,
  },
  clipStats: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  clipStatText: {
    fontSize: 12,
    color: SKATE.colors.gray,
  },
  clipUser: {
    fontSize: 12,
    color: SKATE.colors.gray,
  },
  videoModal: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.9)",
    alignItems: "center",
    justifyContent: "center",
    padding: SKATE.spacing.lg,
  },
  videoModalContent: {
    width: "100%",
    maxWidth: 400,
    backgroundColor: SKATE.colors.grime,
    borderRadius: SKATE.borderRadius.lg,
    overflow: "hidden",
  },
  videoModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: SKATE.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: SKATE.colors.gray,
  },
  videoModalTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: SKATE.colors.lightGray,
  },
  videoPlayer: {
    aspectRatio: 9 / 16,
    backgroundColor: SKATE.colors.ink,
  },
});
