/**
 * Default skateparks and legendary skate spots.
 * These are pre-populated so users see real locations on the map immediately.
 * All coordinates are for real, well-known skateparks and street spots.
 */

export interface DefaultSpot {
  name: string;
  description: string;
  spotType:
    | "park"
    | "street"
    | "bowl"
    | "diy"
    | "stairs"
    | "ledge"
    | "rail"
    | "gap"
    | "mini-ramp"
    | "vert";
  tier: "bronze" | "silver" | "gold" | "legendary";
  lat: number;
  lng: number;
  address: string;
  city: string;
  state: string;
  country: string;
}

export const defaultSpots: DefaultSpot[] = [
  // === LEGENDARY STREET SPOTS ===
  {
    name: "Hubba Hideout",
    description:
      "The legendary hubba ledge in San Francisco. One of the most iconic skate spots in history, featured in countless video parts. The namesake of SkateHubba.",
    spotType: "ledge",
    tier: "legendary",
    lat: 37.7855,
    lng: -122.399,
    address: "425 Mission St",
    city: "San Francisco",
    state: "CA",
    country: "USA",
  },
  {
    name: "LOVE Park",
    description:
      "JFK Plaza in Philadelphia, one of the most famous skate spots in the world. Popularized by legends like Stevie Williams and Josh Kalis.",
    spotType: "street",
    tier: "legendary",
    lat: 39.9543,
    lng: -75.1658,
    address: "1599 John F Kennedy Blvd",
    city: "Philadelphia",
    state: "PA",
    country: "USA",
  },
  {
    name: "Brooklyn Banks",
    description:
      "Iconic street spot under the Brooklyn Bridge in Manhattan. A cornerstone of East Coast skateboarding since the 1980s.",
    spotType: "street",
    tier: "legendary",
    lat: 40.7102,
    lng: -74.0019,
    address: "Brooklyn Bridge, Park Row",
    city: "New York",
    state: "NY",
    country: "USA",
  },
  {
    name: "El Toro 20-Stair",
    description:
      "The infamous 20-stair set at El Toro High School in Lake Forest, CA. One of the gnarliest stair sets ever skated.",
    spotType: "stairs",
    tier: "legendary",
    lat: 33.639,
    lng: -117.686,
    address: "25255 Toledo Way",
    city: "Lake Forest",
    state: "CA",
    country: "USA",
  },
  {
    name: "Hollywood High 16-Stair",
    description:
      "The famous 16-stair set at Hollywood High School. A proving ground for generations of skaters.",
    spotType: "stairs",
    tier: "legendary",
    lat: 34.1017,
    lng: -118.3387,
    address: "1521 N Highland Ave",
    city: "Los Angeles",
    state: "CA",
    country: "USA",
  },
  {
    name: "Wallenberg 4-Block",
    description:
      "The massive 4-block gap and stair set at Wallenberg High School in San Francisco. Scene of some of the biggest tricks in skateboarding.",
    spotType: "stairs",
    tier: "legendary",
    lat: 37.723,
    lng: -122.458,
    address: "40 Vega St",
    city: "San Francisco",
    state: "CA",
    country: "USA",
  },
  {
    name: "Carlsbad Gap",
    description:
      "The legendary gap at Carlsbad High School. One of the most famous gaps in skateboarding history.",
    spotType: "gap",
    tier: "legendary",
    lat: 33.164,
    lng: -117.328,
    address: "3557 Lancer Way",
    city: "Carlsbad",
    state: "CA",
    country: "USA",
  },
  {
    name: "Clipper Ledge",
    description:
      "San Francisco's famous Clipper ledge, a steep downhill hubba. Considered one of the scariest spots in skating.",
    spotType: "ledge",
    tier: "legendary",
    lat: 37.739,
    lng: -122.435,
    address: "Clipper St & Dolores St",
    city: "San Francisco",
    state: "CA",
    country: "USA",
  },
  {
    name: "EMB (Embarcadero)",
    description:
      "The Embarcadero plaza in San Francisco. Birthplace of modern street skating in the late 80s and 90s. Featured in every classic skate video.",
    spotType: "street",
    tier: "legendary",
    lat: 37.7945,
    lng: -122.396,
    address: "Justin Herman Plaza, The Embarcadero",
    city: "San Francisco",
    state: "CA",
    country: "USA",
  },
  {
    name: "Pulaski Park",
    description:
      "Freedom Plaza / Pulaski Park in Washington DC. A legendary street spot with smooth ground and iconic ledges.",
    spotType: "street",
    tier: "legendary",
    lat: 38.8953,
    lng: -77.03,
    address: "1455 Pennsylvania Ave NW",
    city: "Washington",
    state: "DC",
    country: "USA",
  },

  // === FAMOUS SKATEPARKS ===
  {
    name: "Venice Beach Skatepark",
    description:
      "World-famous skatepark right on the Venice Beach boardwalk. Features a snake run, deep bowl, and street section.",
    spotType: "park",
    tier: "gold",
    lat: 33.985,
    lng: -118.472,
    address: "1800 Ocean Front Walk",
    city: "Venice",
    state: "CA",
    country: "USA",
  },
  {
    name: "Burnside Skatepark",
    description:
      "The original DIY skatepark under the Burnside Bridge in Portland. Built by skaters, for skaters, since 1990.",
    spotType: "diy",
    tier: "legendary",
    lat: 45.5225,
    lng: -122.663,
    address: "SE 2nd Ave & E Burnside St",
    city: "Portland",
    state: "OR",
    country: "USA",
  },
  {
    name: "FDR Skatepark",
    description:
      "DIY skatepark under the I-95 overpass in Philadelphia. One of the best DIY parks on the East Coast.",
    spotType: "diy",
    tier: "gold",
    lat: 39.9172,
    lng: -75.1778,
    address: "1500 Pattison Ave",
    city: "Philadelphia",
    state: "PA",
    country: "USA",
  },
  {
    name: "Kona Skatepark",
    description:
      "The oldest continuously operating skatepark in the US, open since 1977. A piece of skateboarding history in Jacksonville.",
    spotType: "park",
    tier: "legendary",
    lat: 30.3167,
    lng: -81.62,
    address: "8739 Kona Ave",
    city: "Jacksonville",
    state: "FL",
    country: "USA",
  },
  {
    name: "Skatepark of Tampa (SPoT)",
    description:
      "Home of the annual Tampa Pro and Tampa Am contests. One of the most important skateparks in competitive skating.",
    spotType: "park",
    tier: "legendary",
    lat: 27.958,
    lng: -82.4593,
    address: "4215 E Columbus Dr",
    city: "Tampa",
    state: "FL",
    country: "USA",
  },
  {
    name: "Stoner Skate Plaza",
    description:
      "Public skate plaza in West Los Angeles with street-style obstacles, ledges, rails, and smooth ground.",
    spotType: "park",
    tier: "gold",
    lat: 34.0367,
    lng: -118.4483,
    address: "1835 Stoner Ave",
    city: "Los Angeles",
    state: "CA",
    country: "USA",
  },
  {
    name: "LES Coleman Skatepark",
    description:
      "Public skatepark on the Lower East Side of Manhattan. The go-to park for NYC skaters.",
    spotType: "park",
    tier: "gold",
    lat: 40.7208,
    lng: -73.9885,
    address: "62 Monroe St",
    city: "New York",
    state: "NY",
    country: "USA",
  },
  {
    name: "Burnham Skatepark",
    description:
      "Chicago's premier skatepark along the lakefront at Grant Park. Modern design with a variety of terrain.",
    spotType: "park",
    tier: "gold",
    lat: 41.8613,
    lng: -87.619,
    address: "350 E Monroe St",
    city: "Chicago",
    state: "IL",
    country: "USA",
  },
  {
    name: "Louisville Extreme Park",
    description:
      "One of the largest free public skateparks in the US. Features a massive concrete bowl, street course, and vert ramp.",
    spotType: "park",
    tier: "gold",
    lat: 38.2605,
    lng: -85.741,
    address: "601 Franklin Ave",
    city: "Louisville",
    state: "KY",
    country: "USA",
  },
  {
    name: "House Park Skatepark",
    description:
      "Austin's famous downtown skatepark. A hub for the Texas skate scene with great street and transition terrain.",
    spotType: "park",
    tier: "gold",
    lat: 30.2749,
    lng: -97.737,
    address: "1213 Shoal Creek Blvd",
    city: "Austin",
    state: "TX",
    country: "USA",
  },
  {
    name: "Denver Skatepark",
    description:
      "Large downtown Denver skatepark with 60,000 sq ft of terrain. One of the biggest free skateparks in the country.",
    spotType: "park",
    tier: "gold",
    lat: 39.7561,
    lng: -105.0006,
    address: "2205 19th St",
    city: "Denver",
    state: "CO",
    country: "USA",
  },
  {
    name: "Lake Cunningham Skatepark",
    description:
      "One of the largest skateparks in California at 68,000 sq ft. World-class bowls and street sections in San Jose.",
    spotType: "park",
    tier: "gold",
    lat: 37.3358,
    lng: -121.806,
    address: "2305 S White Rd",
    city: "San Jose",
    state: "CA",
    country: "USA",
  },
  {
    name: "Etnies Skatepark",
    description:
      "The largest free public skatepark in California. 62,000 sq ft of concrete designed by California Skateparks.",
    spotType: "park",
    tier: "gold",
    lat: 33.64,
    lng: -117.672,
    address: "20028 Lake Forest Dr",
    city: "Lake Forest",
    state: "CA",
    country: "USA",
  },
  {
    name: "Paine's Park",
    description:
      "Modern skate-friendly public plaza along the Schuylkill River Trail in Philadelphia. Designed with skaters in mind.",
    spotType: "park",
    tier: "silver",
    lat: 39.964,
    lng: -75.181,
    address: "2400 B St",
    city: "Philadelphia",
    state: "PA",
    country: "USA",
  },
  {
    name: "Marginal Way Skatepark",
    description:
      "Seattle's largest skatepark with bowls, a street plaza, and transition sections. Located in the SODO neighborhood.",
    spotType: "park",
    tier: "gold",
    lat: 47.572,
    lng: -122.3555,
    address: "2450 Marginal Way S",
    city: "Seattle",
    state: "WA",
    country: "USA",
  },
  {
    name: "Pier 62 Skatepark",
    description:
      "Skatepark on the Hudson River in Manhattan with views of the waterfront. Part of Hudson River Park.",
    spotType: "park",
    tier: "silver",
    lat: 40.746,
    lng: -74.007,
    address: "Pier 62, Hudson River Park",
    city: "New York",
    state: "NY",
    country: "USA",
  },
  {
    name: "Owl's Head Skatepark",
    description:
      "Popular outdoor skatepark in Bay Ridge, Brooklyn with bowls, rails, and street obstacles.",
    spotType: "park",
    tier: "silver",
    lat: 40.643,
    lng: -74.029,
    address: "68th St & Colonial Rd",
    city: "Brooklyn",
    state: "NY",
    country: "USA",
  },
  {
    name: "Vans Off The Wall Skatepark",
    description:
      "Indoor skatepark in Orange, CA run by Vans. Features a Combi pool replica, mini ramp, and street course.",
    spotType: "park",
    tier: "gold",
    lat: 33.787,
    lng: -117.849,
    address: "20 City Blvd W",
    city: "Orange",
    state: "CA",
    country: "USA",
  },
  {
    name: "Woodward West",
    description:
      "World-class action sports training facility in Tehachapi, CA. Indoor and outdoor parks, camps, and coaching.",
    spotType: "park",
    tier: "gold",
    lat: 35.132,
    lng: -118.449,
    address: "28700 Stallion Springs Dr",
    city: "Tehachapi",
    state: "CA",
    country: "USA",
  },
  {
    name: "Woodward Pennsylvania",
    description:
      "The original Woodward camp in Central PA. Legendary training grounds for skaters, BMXers, and more since 1970.",
    spotType: "park",
    tier: "gold",
    lat: 40.962,
    lng: -77.371,
    address: "134 Sports Camp Dr",
    city: "Woodward",
    state: "PA",
    country: "USA",
  },
  {
    name: "Ed Benedict Skatepark",
    description:
      "Popular Portland skatepark with smooth concrete bowls and street sections. A Pacific Northwest favorite.",
    spotType: "park",
    tier: "silver",
    lat: 45.492,
    lng: -122.614,
    address: "SE Powell Blvd & SE 104th Ave",
    city: "Portland",
    state: "OR",
    country: "USA",
  },
  {
    name: "Ann Arbor Skatepark",
    description:
      "Modern concrete skatepark in Veterans Memorial Park. A top destination for skaters in the Midwest.",
    spotType: "park",
    tier: "silver",
    lat: 42.266,
    lng: -83.749,
    address: "2150 Jackson Ave",
    city: "Ann Arbor",
    state: "MI",
    country: "USA",
  },
  {
    name: "Shaw Millennium Park",
    description:
      "One of the largest outdoor skateparks in the world at 75,000 sq ft, located in Calgary, Canada.",
    spotType: "park",
    tier: "gold",
    lat: 51.042,
    lng: -114.09,
    address: "333 9 Ave SW",
    city: "Calgary",
    state: "AB",
    country: "Canada",
  },
  {
    name: "Lauridsen Skatepark",
    description:
      "The largest open skatepark in the US at 88,000 sq ft. Located along the Des Moines River with world-class terrain.",
    spotType: "park",
    tier: "gold",
    lat: 41.581,
    lng: -93.631,
    address: "201 SW 2nd St",
    city: "Des Moines",
    state: "IA",
    country: "USA",
  },

  // === LEGENDARY INTERNATIONAL STREET SPOTS ===
  {
    name: "MACBA (Museu d'Art Contemporani)",
    description:
      "The plaza in front of Barcelona's contemporary art museum. The most famous skate spot in Europe, featured in every major skate video since the 2000s.",
    spotType: "street",
    tier: "legendary",
    lat: 41.3834,
    lng: 2.167,
    address: "Plaça dels Àngels, 1",
    city: "Barcelona",
    state: "Catalonia",
    country: "Spain",
  },
  {
    name: "Southbank Undercroft",
    description:
      "London's iconic skate spot under the Queen Elizabeth Hall. Has been skated since the 1970s and fought to be preserved as a cultural landmark.",
    spotType: "street",
    tier: "legendary",
    lat: 51.5065,
    lng: -0.1163,
    address: "Belvedere Rd, South Bank",
    city: "London",
    state: "",
    country: "UK",
  },
  {
    name: "Paral·lel (Tres Chimeneas)",
    description:
      "Famous Barcelona street spot with marble ledges near Avinguda del Paral·lel. A staple of European skate videos.",
    spotType: "ledge",
    tier: "gold",
    lat: 41.374,
    lng: 2.153,
    address: "Avinguda del Paral·lel",
    city: "Barcelona",
    state: "Catalonia",
    country: "Spain",
  },
  {
    name: "Flushing Meadows Skatepark",
    description:
      "Large public skatepark in Queens, NYC near the Unisphere. Features bowls, street sections, and smooth concrete.",
    spotType: "park",
    tier: "gold",
    lat: 40.7465,
    lng: -73.8456,
    address: "131-04 Meridian Rd",
    city: "New York",
    state: "NY",
    country: "USA",
  },
  {
    name: "Sants Station 3-Block",
    description:
      "The famous three-block set outside Barcelona Sants train station. Appeared in countless European skate parts.",
    spotType: "stairs",
    tier: "gold",
    lat: 41.379,
    lng: 2.14,
    address: "Plaça dels Països Catalans",
    city: "Barcelona",
    state: "Catalonia",
    country: "Spain",
  },
  {
    name: "Pier 7",
    description:
      "Famous waterfront ledge spot on the San Francisco Embarcadero. Perfect marble ledges with a bay view.",
    spotType: "ledge",
    tier: "legendary",
    lat: 37.7983,
    lng: -122.394,
    address: "Pier 7, The Embarcadero",
    city: "San Francisco",
    state: "CA",
    country: "USA",
  },
  {
    name: "Westblaak",
    description:
      "Rotterdam's legendary street spot with a long row of marble ledges. One of the best spots in the Netherlands.",
    spotType: "ledge",
    tier: "gold",
    lat: 51.9178,
    lng: 4.4805,
    address: "Westblaak",
    city: "Rotterdam",
    state: "",
    country: "Netherlands",
  },
  {
    name: "Leeside DIY",
    description:
      "Famous DIY skatepark under a bridge in Vancouver. Built and maintained by local skaters for over 15 years.",
    spotType: "diy",
    tier: "gold",
    lat: 49.279,
    lng: -123.044,
    address: "Under the Georgia Viaduct",
    city: "Vancouver",
    state: "BC",
    country: "Canada",
  },
  {
    name: "Lincoln Memorial Steps",
    description:
      "The plaza and steps around the Lincoln Memorial reflecting pool in DC. Classic street spot from early 2000s videos.",
    spotType: "stairs",
    tier: "gold",
    lat: 38.8893,
    lng: -77.0502,
    address: "2 Lincoln Memorial Cir NW",
    city: "Washington",
    state: "DC",
    country: "USA",
  },
  {
    name: "China Banks",
    description:
      "Classic San Francisco street spot in Chinatown with banked walls and ledges. Old-school SF skate history.",
    spotType: "street",
    tier: "gold",
    lat: 37.797,
    lng: -122.406,
    address: "Walter U Lum Pl",
    city: "San Francisco",
    state: "CA",
    country: "USA",
  },
  {
    name: "Sheldon Court (JKwon)",
    description:
      "Famous Philadelphia ledge spot. One of the most filmed spots in East Coast skating with perfect waxed granite ledges.",
    spotType: "ledge",
    tier: "gold",
    lat: 39.953,
    lng: -75.17,
    address: "34th & Walnut St",
    city: "Philadelphia",
    state: "PA",
    country: "USA",
  },
  {
    name: "Melbourne Museum Plaza",
    description:
      "The plaza outside the Melbourne Museum with smooth ground and ledges. The heart of Australian street skating.",
    spotType: "street",
    tier: "gold",
    lat: -37.8032,
    lng: 144.9717,
    address: "11 Nicholson St, Carlton",
    city: "Melbourne",
    state: "VIC",
    country: "Australia",
  },
  {
    name: "Bay 66 Skatepark",
    description:
      "West London's famous outdoor skatepark under the Westway flyover. A hub of London's skate scene.",
    spotType: "park",
    tier: "gold",
    lat: 51.5155,
    lng: -0.2092,
    address: "66 Acklam Rd",
    city: "London",
    state: "",
    country: "UK",
  },
  {
    name: "Bondi Skatepark",
    description:
      "Iconic beachside skatepark at Bondi Beach, Sydney. Concrete bowls with ocean views.",
    spotType: "bowl",
    tier: "gold",
    lat: -33.892,
    lng: 151.274,
    address: "Ramsgate Ave, Bondi Beach",
    city: "Sydney",
    state: "NSW",
    country: "Australia",
  },
  {
    name: "Bercy Skatepark",
    description:
      "Paris's premier outdoor skatepark in the 12th arrondissement. A gathering spot for the French skate community.",
    spotType: "park",
    tier: "gold",
    lat: 48.8327,
    lng: 2.386,
    address: "Parc de Bercy",
    city: "Paris",
    state: "",
    country: "France",
  },
  {
    name: "Trocadéro",
    description:
      "The plaza across from the Eiffel Tower. Smooth marble ground and gaps make it a legendary Parisian street spot.",
    spotType: "street",
    tier: "gold",
    lat: 48.8617,
    lng: 2.2885,
    address: "Place du Trocadéro",
    city: "Paris",
    state: "",
    country: "France",
  },
  {
    name: "Hiroshima 3-Block",
    description:
      "Famous three-block hubba in Hiroshima, Japan. One of the most iconic spots in Japanese skateboarding.",
    spotType: "ledge",
    tier: "gold",
    lat: 34.394,
    lng: 132.459,
    address: "Hiroshima Peace Memorial Park",
    city: "Hiroshima",
    state: "",
    country: "Japan",
  },
  {
    name: "Miyashita Park Skatepark",
    description:
      "Public skatepark in the heart of Shibuya, Tokyo. Rooftop park with ledges, rails, and a mini ramp.",
    spotType: "park",
    tier: "gold",
    lat: 35.663,
    lng: 139.698,
    address: "6-20-10 Jingumae, Shibuya",
    city: "Tokyo",
    state: "",
    country: "Japan",
  },
  {
    name: "Fælledparken Skatepark",
    description:
      "Copenhagen's beloved public skatepark in Østerbro. One of the best skateparks in Scandinavia with great concrete.",
    spotType: "park",
    tier: "gold",
    lat: 55.701,
    lng: 12.569,
    address: "Fælledparken",
    city: "Copenhagen",
    state: "",
    country: "Denmark",
  },
  {
    name: "Skatehalle Berlin",
    description:
      "Berlin's famous indoor skatepark in Friedrichshain. A winter haven for European skaters.",
    spotType: "park",
    tier: "gold",
    lat: 52.507,
    lng: 13.4543,
    address: "Revaler Str. 99",
    city: "Berlin",
    state: "",
    country: "Germany",
  },
  {
    name: "Museumplein",
    description:
      "The large open square between Amsterdam's museums. Smooth flat ground and ledges make it an iconic Dutch skate spot.",
    spotType: "street",
    tier: "gold",
    lat: 52.358,
    lng: 4.883,
    address: "Museumplein",
    city: "Amsterdam",
    state: "",
    country: "Netherlands",
  },
  {
    name: "Les Ursulines",
    description:
      "Famous Lyon, France street spot with perfect ledges and smooth ground. A European skate mecca.",
    spotType: "ledge",
    tier: "gold",
    lat: 45.7534,
    lng: 4.828,
    address: "Rue des Ursulines",
    city: "Lyon",
    state: "",
    country: "France",
  },
  {
    name: "Rådhuspladsen",
    description:
      "Copenhagen City Hall Square. Perfect granite ledges and smooth ground in the center of the city.",
    spotType: "street",
    tier: "gold",
    lat: 55.6761,
    lng: 12.5683,
    address: "Rådhuspladsen",
    city: "Copenhagen",
    state: "",
    country: "Denmark",
  },

  // === MORE US STREET SPOTS ===
  {
    name: "Black Hubba (San Francisco)",
    description:
      "The famous black marble hubba at the SF Federal Building. Featured in countless pro video parts.",
    spotType: "ledge",
    tier: "gold",
    lat: 37.78,
    lng: -122.417,
    address: "50 United Nations Plaza",
    city: "San Francisco",
    state: "CA",
    country: "USA",
  },
  {
    name: "3rd & Army (San Francisco)",
    description:
      "Classic SF warehouse district spot with banks and ledges. Old-school San Francisco street skating.",
    spotType: "street",
    tier: "silver",
    lat: 37.768,
    lng: -122.391,
    address: "3rd St & Army St",
    city: "San Francisco",
    state: "CA",
    country: "USA",
  },
  {
    name: "Courthouse (LA)",
    description:
      "The famous LA courthouse with its iconic handrails and stair sets. Endless pro footage filmed here.",
    spotType: "rail",
    tier: "gold",
    lat: 34.052,
    lng: -118.244,
    address: "111 N Hill St",
    city: "Los Angeles",
    state: "CA",
    country: "USA",
  },
  {
    name: "Wilshire 15 (LA)",
    description:
      "The famous Wilshire Boulevard 15-stair in Los Angeles. One of the most filmed stair sets in skateboarding.",
    spotType: "stairs",
    tier: "gold",
    lat: 34.0628,
    lng: -118.3085,
    address: "5900 Wilshire Blvd",
    city: "Los Angeles",
    state: "CA",
    country: "USA",
  },
  {
    name: "Rincon Skatepark",
    description:
      "Popular San Francisco skatepark near the Bay Bridge with street and transition terrain.",
    spotType: "park",
    tier: "silver",
    lat: 37.7905,
    lng: -122.389,
    address: "The Embarcadero & Folsom St",
    city: "San Francisco",
    state: "CA",
    country: "USA",
  },
  {
    name: "Cherry Park",
    description:
      "Famous NYC street spot in the Lower East Side with banks, ledges, and a long manual pad.",
    spotType: "street",
    tier: "silver",
    lat: 40.713,
    lng: -73.987,
    address: "Cherry St & Pike Slip",
    city: "New York",
    state: "NY",
    country: "USA",
  },
  {
    name: "Hubba Hideout 2.0 (SF Federal)",
    description:
      "The modern replacement hubba ledge near the original Hubba Hideout location. Keeping the SF ledge tradition alive.",
    spotType: "ledge",
    tier: "silver",
    lat: 37.7852,
    lng: -122.3985,
    address: "425 Mission St (south side)",
    city: "San Francisco",
    state: "CA",
    country: "USA",
  },
  {
    name: "Lockwood (JKwon Rail)",
    description:
      "The famous kinked rail in Lockwood, California. One of the most iconic rails in skateboarding, made famous by countless pros.",
    spotType: "rail",
    tier: "gold",
    lat: 34.067,
    lng: -118.229,
    address: "Lockwood Ave",
    city: "Los Angeles",
    state: "CA",
    country: "USA",
  },

  // === MORE US SKATEPARKS ===
  {
    name: "Arvada Skatepark",
    description:
      "Modern concrete skatepark in Arvada, Colorado with flow bowls and street sections.",
    spotType: "park",
    tier: "silver",
    lat: 39.8028,
    lng: -105.0875,
    address: "6790 Wadsworth Bypass",
    city: "Arvada",
    state: "CO",
    country: "USA",
  },
  {
    name: "Sheldon Skatepark (Sun Valley)",
    description:
      "One of the best skateparks in Idaho. Modern concrete design in a beautiful mountain town.",
    spotType: "park",
    tier: "silver",
    lat: 43.6953,
    lng: -114.351,
    address: "201 1st Ave N",
    city: "Ketchum",
    state: "ID",
    country: "USA",
  },
  {
    name: "Channel Street Skatepark",
    description:
      "San Pedro's famous concrete park with one of the best snake runs on the West Coast.",
    spotType: "park",
    tier: "gold",
    lat: 33.732,
    lng: -118.285,
    address: "550 S Palos Verdes St",
    city: "San Pedro",
    state: "CA",
    country: "USA",
  },
  {
    name: "Providence Skatepark",
    description:
      "Large concrete skatepark in Rhode Island with street, transition, and bowl sections.",
    spotType: "park",
    tier: "silver",
    lat: 41.824,
    lng: -71.4128,
    address: "175 India St",
    city: "Providence",
    state: "RI",
    country: "USA",
  },

  // === LEGENDARY INTERNATIONAL SKATEPARKS ===
  {
    name: "Stockwell Skatepark (Brixton Beach)",
    description:
      "London's oldest surviving skatepark, built in 1978. A concrete masterpiece and cultural landmark.",
    spotType: "park",
    tier: "legendary",
    lat: 51.468,
    lng: -0.122,
    address: "Stockwell Park Walk",
    city: "London",
    state: "",
    country: "UK",
  },
  {
    name: "Mar Bella Skatepark",
    description:
      "Barcelona beachside skatepark with bowls and street terrain. Skate with a Mediterranean sea view.",
    spotType: "park",
    tier: "gold",
    lat: 41.394,
    lng: 2.21,
    address: "Passeig Marítim de la Mar Bella",
    city: "Barcelona",
    state: "Catalonia",
    country: "Spain",
  },
  {
    name: "Vans Skatepark (Huntington Beach)",
    description:
      "Vans' flagship 15,000 sq ft indoor skatepark at the Off The Wall Skatepark in Orange County.",
    spotType: "park",
    tier: "gold",
    lat: 33.6595,
    lng: -117.9988,
    address: "7471 Center Ave",
    city: "Huntington Beach",
    state: "CA",
    country: "USA",
  },
];
