import { StyleSheet } from "react-native";
import { SKATE } from "@/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: SKATE.colors.ink,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: SKATE.spacing.lg,
    paddingBottom: SKATE.spacing.lg,
    backgroundColor: SKATE.colors.grime,
  },
  closeButton: {
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
  },
  headerContent: {
    flex: 1,
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: SKATE.colors.white,
    letterSpacing: 2,
  },
  trickToMatch: {
    fontSize: 14,
    color: SKATE.colors.orange,
    marginTop: SKATE.spacing.xs,
    fontWeight: "600",
  },
  placeholder: {
    width: 44,
  },
  cameraContainer: {
    flex: 1,
    position: "relative",
  },
  camera: {
    flex: 1,
  },
  recordingOverlay: {
    position: "absolute",
    top: SKATE.spacing.lg,
    left: 0,
    right: 0,
    alignItems: "center",
    gap: SKATE.spacing.sm,
  },
  recordingIndicator: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    paddingHorizontal: SKATE.spacing.md,
    paddingVertical: SKATE.spacing.sm,
    borderRadius: SKATE.borderRadius.full,
    gap: SKATE.spacing.sm,
  },
  recordingDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: SKATE.colors.blood,
  },
  recordingText: {
    color: SKATE.colors.blood,
    fontWeight: "bold",
    fontSize: 14,
  },
  timerText: {
    color: SKATE.colors.white,
    fontSize: 16,
    fontWeight: "600",
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    paddingHorizontal: SKATE.spacing.md,
    paddingVertical: SKATE.spacing.xs,
    borderRadius: SKATE.borderRadius.sm,
  },
  progressBarContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 4,
    backgroundColor: SKATE.colors.darkGray,
  },
  progressBar: {
    height: "100%",
    backgroundColor: SKATE.colors.blood,
  },
  previewContainer: {
    flex: 1,
    backgroundColor: SKATE.colors.ink,
  },
  preview: {
    flex: 1,
  },
  controls: {
    padding: SKATE.spacing.xl,
    alignItems: "center",
    backgroundColor: SKATE.colors.grime,
  },
  recordButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: SKATE.colors.blood,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 4,
    borderColor: SKATE.colors.white,
  },
  recordingButton: {
    backgroundColor: SKATE.colors.orange,
  },
  actionButtons: {
    flexDirection: "row",
    gap: SKATE.spacing.lg,
    width: "100%",
  },
  actionButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: SKATE.spacing.sm,
    backgroundColor: SKATE.colors.darkGray,
    paddingVertical: SKATE.spacing.lg,
    borderRadius: SKATE.borderRadius.md,
    minHeight: SKATE.accessibility.minimumTouchTarget,
  },
  submitButton: {
    backgroundColor: SKATE.colors.orange,
  },
  actionButtonText: {
    color: SKATE.colors.white,
    fontSize: 16,
    fontWeight: "bold",
  },
  uploadProgressText: {
    color: SKATE.colors.white,
    fontSize: 18,
    fontWeight: "bold",
  },
  instructions: {
    padding: SKATE.spacing.lg,
    backgroundColor: SKATE.colors.ink,
  },
  instructionText: {
    color: SKATE.colors.lightGray,
    fontSize: 14,
    textAlign: "center",
  },
  permissionDenied: {
    flex: 1,
    backgroundColor: SKATE.colors.ink,
    justifyContent: "center",
    alignItems: "center",
    padding: SKATE.spacing.xxl,
  },
  permissionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: SKATE.colors.white,
    marginTop: SKATE.spacing.xl,
    marginBottom: SKATE.spacing.md,
  },
  permissionText: {
    fontSize: 14,
    color: SKATE.colors.lightGray,
    textAlign: "center",
    marginBottom: SKATE.spacing.xl,
  },
  backButton: {
    backgroundColor: SKATE.colors.orange,
    paddingHorizontal: SKATE.spacing.xxl,
    paddingVertical: SKATE.spacing.md,
    borderRadius: SKATE.borderRadius.md,
    minHeight: SKATE.accessibility.minimumTouchTarget,
    justifyContent: "center",
  },
  backButtonText: {
    color: SKATE.colors.white,
    fontSize: 16,
    fontWeight: "bold",
  },
  trickInputOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    justifyContent: "center",
    alignItems: "center",
    padding: SKATE.spacing.xl,
  },
  trickInputCard: {
    backgroundColor: SKATE.colors.grime,
    borderRadius: SKATE.borderRadius.lg,
    padding: SKATE.spacing.xl,
    width: "100%",
    maxWidth: 340,
  },
  trickInputTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: SKATE.colors.white,
    textAlign: "center",
    marginBottom: SKATE.spacing.lg,
  },
  trickInput: {
    backgroundColor: SKATE.colors.ink,
    borderWidth: 2,
    borderColor: SKATE.colors.darkGray,
    borderRadius: SKATE.borderRadius.md,
    padding: SKATE.spacing.md,
    color: SKATE.colors.white,
    fontSize: 16,
    marginBottom: SKATE.spacing.lg,
  },
  trickInputButtons: {
    flexDirection: "row",
    gap: SKATE.spacing.md,
  },
  trickInputButtonPrimary: {
    flex: 1,
    backgroundColor: SKATE.colors.orange,
    paddingVertical: SKATE.spacing.md,
    borderRadius: SKATE.borderRadius.md,
    alignItems: "center",
    minHeight: SKATE.accessibility.minimumTouchTarget,
    justifyContent: "center",
  },
  trickInputButtonSecondary: {
    flex: 1,
    backgroundColor: SKATE.colors.darkGray,
    paddingVertical: SKATE.spacing.md,
    borderRadius: SKATE.borderRadius.md,
    alignItems: "center",
    minHeight: SKATE.accessibility.minimumTouchTarget,
    justifyContent: "center",
  },
  trickInputButtonText: {
    color: SKATE.colors.white,
    fontSize: 16,
    fontWeight: "bold",
  },
  trickInputButtonTextSecondary: {
    color: SKATE.colors.lightGray,
    fontSize: 16,
    fontWeight: "600",
  },
});
