/**
 * Vercel Serverless Function — API entry point
 *
 * This file is committed to git so Vercel detects it as a serverless function.
 * At runtime it dynamically imports the esbuild-bundled handler (_handler.mjs)
 * which resolves all @shared/* path aliases that Vercel's TypeScript compiler
 * cannot handle.
 *
 * Build pipeline: server/vercel-handler.ts → esbuild → api/_handler.mjs
 */
import type { IncomingMessage, ServerResponse } from "node:http";

type Handler = (req: IncomingMessage, res: ServerResponse) => void;

let handler: Handler | null = null;
let loadError: Error | null = null;
let handlerConfig: Record<string, unknown> = {};

try {
  // @ts-expect-error — _handler.mjs is a build artifact generated by esbuild
  const mod = await import("./_handler.mjs");
  handler = mod.default;
  if (mod.config) handlerConfig = mod.config;
} catch (err) {
  loadError = err instanceof Error ? err : new Error(String(err));
  console.error("[api/index] Failed to load bundled handler:", loadError.message);
  if (loadError.stack) {
    console.error("[api/index] Stack:", loadError.stack);
  }
}

export const config = {
  maxDuration: 30,
  memory: 1024,
  ...handlerConfig,
};

export default function serverHandler(req: IncomingMessage, res: ServerResponse) {
  if (handler) {
    return handler(req, res);
  }

  const isDeployed = !!process.env.VERCEL_ENV;
  const body = JSON.stringify({
    error: "HANDLER_LOAD_FAILED",
    message: "The API handler bundle failed to load. Check build logs.",
    detail: isDeployed ? undefined : loadError?.message,
    hint: "Ensure scripts/build-server.mjs ran successfully during the build step.",
  });

  res.writeHead(500, {
    "Content-Type": "application/json",
    "Content-Length": String(Buffer.byteLength(body)),
    "X-Frame-Options": "DENY",
    "X-Content-Type-Options": "nosniff",
  });
  res.end(body);
}
